site_name: My MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo-blackred.png
  favicon: assets/logo-blackred.png
  features:
    - navigation.footer
  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
    primary: blue grey
    accent: red

# Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
    primary: amber
    accent: orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true

  - admonition
  - pymdownx.details

extra:
  social: 
    - icon: simple/x
      link: https://x.com/sureailabs

copyright: Copyright &copy; 2025 Martine Balcaen